from CMSusingOOPS import *
from tkinter import *
from tkinter import messagebox

def addHandler():

    cus=Customer()  #cus=1000,cus.id=0,cus.name=0,cus.age=0,cus.mob=0
    cus.id=var_id.get()
    cus.name=var_name.get()
    cus.age=var_age.get()
    cus.mob=var_mob.get()
    cus.addCustomer()
    messagebox.showinfo("My CMS","Customer Added Successfully")
    var_id.set("")
    var_name.set("")
    var_age.set("")
    var_mob.set("")
def searchHandler():
    cus=Customer()
    cus.id=var_id.get()
    cus.searchCustomer()
    var_name.set(cus.name)
    var_age.set(cus.age)
    var_mob.set(cus.mob)
def deleteHandler():
    cus=Customer()
    cus.id=var_id.get()
    cus.deleteCustomer()
    messagebox.showinfo("CMS","Customer Deleted Successfully")
    var_id.set("")
def allHandler():
    root_all=Tk()
    lbl_id_all=Label(root_all,text="CUST ID",bg="Orange",width=15,font=20)
    lbl_id_all.grid(row=0,column=0)
    lbl_name_all = Label(root_all, text="CUST NAME", bg="Orange", width=15,font=20)
    lbl_name_all.grid(row=0, column=1)
    lbl_age_all = Label(root_all, text="CUST AGE", bg="Orange", width=15,font=20)
    lbl_age_all.grid(row=0, column=2)
    lbl_mob_all = Label(root_all, text="CUST MOB", bg="Orange", width=15,font=20)
    lbl_mob_all.grid(row=0, column=3)
    i=1
    for e in Customer.cus_list:
        lbl_id_data=Label(root_all,text=e.id,bg="Yellow",width=15,font=20)
        lbl_id_data.grid(row=i,column=0)
        lbl_name_data = Label(root_all, text=e.name, bg="Yellow", width=15, font=20)
        lbl_name_data.grid(row=i, column=1)
        lbl_age_data = Label(root_all, text=e.age, bg="Yellow", width=15, font=20)
        lbl_age_data.grid(row=i, column=2)
        lbl_mob_data = Label(root_all, text=e.mob, bg="Yellow", width=15, font=20)
        lbl_mob_data.grid(row=i, column=3)
        i+=1
def saveHandler():
    Customer.savetoPickle()
    messagebox.showinfo("CMS","Data saved successfully")
def loadHandler():
    Customer.loadfromPickle()
    messagebox.showinfo("CMS","Data Retrieved successfully")

root=Tk()
root.geometry("600x600")
lbl_id=Label(root,text="Enter Cust ID:",font=20)
lbl_id.grid(row=0,column=0)
lbl_name=Label(root,text="Enter Cust Name:",font=20)
lbl_name.grid(row=1,column=0)
lbl_age=Label(root,text="Enter Cust Age:",font=20)
lbl_age.grid(row=2,column=0)
lbl_mob=Label(root,text="Enter Cust Mob:",font=20)
lbl_mob.grid(row=3,column=0)
var_id=StringVar()
entr_id=Entry(root,textvariable=var_id,font=20)
entr_id.grid(row=0,column=1)
var_name=StringVar()
entr_name=Entry(root,textvariable=var_name,font=20)
entr_name.grid(row=1,column=1)
var_age=StringVar()
entr_age=Entry(root,textvariable=var_age,font=20)
entr_age.grid(row=2,column=1)
var_mob=StringVar()
entr_mob=Entry(root,textvariable=var_mob,font=20)
entr_mob.grid(row=3,column=1)

btn_add=Button(root,text="Add Cust",font=20,width=15,height=2,command=addHandler)
btn_add.grid(row=4,column=0)
btn_search=Button(root,text="Search Cust",font=20,width=15,height=2,command=searchHandler)
btn_search.grid(row=4,column=1)
btn_delete=Button(root,text="Delete Cust",font=20,width=15,height=2,command=deleteHandler)
btn_delete.grid(row=4,column=2)
btn_modify=Button(root,text="Modify Cust",font=20,width=15,height=2)
btn_modify.grid(row=5,column=0)
btn_all=Button(root,text="All Cust",font=20,width=15,height=2,command=allHandler)
btn_all.grid(row=5,column=1)
btn_save=Button(root,text="Save Cust",font=20,width=15,height=2,command=saveHandler)
btn_save.grid(row=5,column=2)
btn_load=Button(root,text="Load Cust",font=20,width=15,height=2,command=loadHandler)
btn_load.grid(row=6,column=0)
root.mainloop()